### ISSUE TITLE
How i can enable plugin

### ISSUE THREAD

**Issue by vladviolentiy** [inpsyde/translation-cache#4]
I install you plugin in wp. how i can enable plugin?

**Comment by bueltge** [comment]
Have you read the readme and his installation how to as MU plugin?
https://github.com/inpsyde/translation-cache#mu-plugin-self-installation

**Comment by vladviolentiy** [comment]
i install via WP plugin manager, i see plugin, but xdebug show, that cache not work

**Comment by bueltge** [comment]
That's not possible. The plugin must! run as mu-plugin, see the readme about this topics and deeper information about why and how.
