### ISSUE TITLE
Why not make the package "wordpress-muplugin"?

### ISSUE THREAD

**Issue by MaximeCulea** [inpsyde/translation-cache#5]
Hi there,

I wanted to see if from your feedback there is any contraindication for installing the package as "wordpress-muplugin" instead of "wordpress-plugin" then copying the stuff to mu-plugin folder.

As it is installed throught composer it could be required to use a mu-require, isn't it?
Anyway, it's only a matter of feedback to better understand this choice.

In advance, thank you for your response!
Cheers

**Comment by bueltge** [comment]
If you use Multisite, yes please use it as mu-plugin. I think is the best choice to use this plugin network-wide.

**Comment by MaximeCulea** [comment]
@bueltge Yeah sure, but my question was more related to the [mu-plugin-self-installation](https://github.com/inpsyde/translation-cache#mu-plugin-self-installation).

**Comment by bueltge** [comment]
I understand your hint so that you will install via Composer as mu-plugin, right? Often users don't have a Multisite and we need the copy in the mu-plugin folder and creation of this directory. So I see no chance to install the plugin always as mu-plugin without effort in support.

**Comment by MaximeCulea** [comment]
Ok I see.

My opinion is, as it is not a plugin as a feature that the client can deactivate, but more related to performances and optinization, I am always installing as mu-plugin, multisite or not ^^

Anyway, thx for the hint.
Cya

**Comment by bueltge** [comment]
Hi @MaximeCulea 
you have right, also our procedure. But lot of users have no knowledge about Multisite and/or mu-plugin folder. Really often we have this topic inside the support, especially for our multilingual solution that has the dependency of a Multisite.

**Comment by MaximeCulea** [comment]
Thank you @bueltge for your time to prcise this.
Yeah, I imagine that with MLP, things go quickly to support when installing is not "usual".

That's why you made it [automagically](https://github.com/inpsyde/translation-cache/blob/master/inpsyde-translation-cache.php#L58).
And to finish, have you been exploring, digging into an other way to install things to muplugin?

**Comment by bueltge** [comment]
We install all plugin and other requirements via Composer, that's our import tool for this step.

**Comment by MaximeCulea** [comment]
I am in the same case as you and that's where I don't get the choice for [`wordpress-plugin`](https://github.com/inpsyde/translation-cache/blob/master/composer.json#L20) instead of `wordpress-muplugin`.
I think that all people handeling plugins via composer are good enough to play with mu-plugins, aren't they ? 🤗
